"""Conversation history -> normalized :class:`AgentEvent` stream.

Every request from a coding agent carries its conversation: Anthropic
``tool_use``/``tool_result`` blocks for Claude Code, and Responses
``function_call``/``*_output`` items for Codex (adapted through
:func:`headroom.intelligence.messages.responses_items_to_messages`). This
module flattens either shape into :class:`HistoryItem` objects, then into
events with deterministic ids. A replayed or retried request maps to the same
ids, and the runtime dispatches only events it has not stored before.

Harness chatter is not user intent: Claude Code ``<system-reminder>`` blocks,
slash-command echoes, and Codex ``<environment_context>`` /
``<user_instructions>`` / AGENTS.md preambles. It is stripped before any
consumer sees user text.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

from .events import AgentEvent, EventType, command_fingerprint
from .families import Family, ToolInvocation, normalize_tool_call
from .ids import stable_id
from .results import outcome_success, parse_test_output

_SYSTEM_REMINDER_RE = re.compile(r"(?s)<system-reminder>.*?</system-reminder>")
_HARNESS_TAG_RE = re.compile(
    r"(?s)<(command-name|command-message|command-args|local-command-stdout|local-command-stderr|"
    r"local-command-caveat|bash-input|bash-stdout|bash-stderr)>.*?</\1>"
)
_CAVEAT_RE = re.compile(r"(?s)^Caveat: The messages below were generated by the user.*?\n\n")
_CODEX_PREAMBLE_RE = re.compile(
    r"(?s)^\s*(?:<environment_context>|<user_instructions>|<INSTRUCTIONS>|"
    r"# AGENTS\.md instructions|<user_shell_command>|<turn_aborted>)"
)
INTERRUPT_RE = re.compile(r"\[Request interrupted by user(?: for tool use)?\]")


def clean_user_text(text: str) -> str:
    """User-authored text with harness noise removed ("" when nothing remains)."""
    if not text:
        return ""
    if _CODEX_PREAMBLE_RE.match(text):
        return ""
    out = _SYSTEM_REMINDER_RE.sub("", text)
    out = _HARNESS_TAG_RE.sub("", out)
    out = _CAVEAT_RE.sub("", out)
    return out.strip()


@dataclass
class HistoryItem:
    kind: str  # user | assistant | call | result
    index: int
    text: str = ""
    call_id: str = ""
    name: str = ""
    input: dict[str, Any] = field(default_factory=dict)
    is_error: bool = False
    interrupted: bool = False
    call_index: int = -1  # message index of the assistant turn that issued the call


def _decode(raw: Any) -> dict[str, Any]:
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str) and raw.strip():
        try:
            val = json.loads(raw)
        except (TypeError, ValueError):
            return {"input": raw}
        return val if isinstance(val, dict) else {"input": raw}
    return {}


def _flatten(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for b in content:
            if isinstance(b, dict) and b.get("type") in ("text", "input_text", "output_text"):
                parts.append(str(b.get("text", "")))
            elif isinstance(b, str):
                parts.append(b)
        return "\n".join(parts)
    return ""


def history_items(messages: list[dict[str, Any]]) -> list[HistoryItem]:
    """Flatten Anthropic-native or chat-shaped messages into ordered items."""
    items: list[HistoryItem] = []
    names: dict[str, tuple[str, dict[str, Any]]] = {}
    turns: dict[str, int] = {}
    for i, msg in enumerate(messages or []):
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        content = msg.get("content")
        if role == "tool":
            cid = str(msg.get("tool_call_id") or "")
            name, inp = names.get(cid, (str(msg.get("name") or ""), {}))
            items.append(
                HistoryItem(
                    "result",
                    i,
                    text=_flatten(content),
                    call_id=cid,
                    name=name,
                    input=inp,
                    call_index=turns.get(cid, i),
                )
            )
            continue
        if role == "system" or role == "developer":
            continue
        texts: list[str] = []
        if isinstance(content, str):
            texts.append(content)
        elif isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type")
                if btype in ("text", "input_text", "output_text"):
                    texts.append(str(block.get("text", "")))
                elif btype == "tool_use":
                    if role == "assistant" and any(t.strip() for t in texts):
                        # Keep block order: a claim made before a tool call precedes it.
                        items.append(HistoryItem("assistant", i, text="\n".join(texts).strip()))
                        texts = []
                    cid = str(block.get("id") or "")
                    name = str(block.get("name") or "")
                    inp = _decode(block.get("input"))
                    names[cid] = (name, inp)
                    turns[cid] = i
                    items.append(
                        HistoryItem("call", i, call_id=cid, name=name, input=inp, call_index=i)
                    )
                elif btype == "tool_result":
                    cid = str(block.get("tool_use_id") or "")
                    name, inp = names.get(cid, ("", {}))
                    items.append(
                        HistoryItem(
                            "result",
                            i,
                            text=_flatten(block.get("content", "")),
                            call_id=cid,
                            name=name,
                            input=inp,
                            is_error=block.get("is_error") is True,
                            call_index=turns.get(cid, i),
                        )
                    )
        for call in msg.get("tool_calls") or []:
            if not isinstance(call, dict):
                continue
            cid = str(call.get("id") or "")
            fn = call.get("function") or {}
            name = str(fn.get("name") or "")
            inp = _decode(fn.get("arguments"))
            names[cid] = (name, inp)
            # Consecutive call-only messages (Codex parallel calls) are one turn.
            prev = messages[i - 1] if i > 0 else None
            turn = i
            if (
                isinstance(prev, dict)
                and prev.get("role") == "assistant"
                and prev.get("tool_calls")
                and not prev.get("content")
            ):
                turn = turns.get(str((prev.get("tool_calls") or [{}])[0].get("id") or ""), i)
            turns[cid] = turn
            items.append(HistoryItem("call", i, call_id=cid, name=name, input=inp, call_index=turn))
        text = "\n".join(t for t in texts if t)
        if role == "user":
            interrupted = bool(INTERRUPT_RE.search(text))
            cleaned = clean_user_text(INTERRUPT_RE.sub("", text))
            if cleaned or interrupted:
                items.append(HistoryItem("user", i, text=cleaned, interrupted=interrupted))
        elif role == "assistant" and text.strip():
            items.append(HistoryItem("assistant", i, text=text.strip()))
    return items


def conversation_root(items: list[HistoryItem]) -> str:
    for it in items:
        if it.kind == "user" and it.text:
            return it.text
    return ""


def _h(text: str) -> str:
    return hashlib.sha256((text or "").encode("utf-8", "surrogatepass")).hexdigest()[:24]


@dataclass
class NormalizeContext:
    workspace_id: str
    session_key: str
    project_root: str = ""
    cwd: str = ""
    now: float = 0.0


def item_event_ids(
    items: list[HistoryItem], session_key: str, seen: Counter[str] | None = None
) -> list[str]:
    """Deterministic id per item (ordinal-disambiguated for repeated text).

    ``seen`` carries the text ordinals of an already-identified prefix so an
    append-only history can be identified incrementally; it is updated.
    """
    seen = Counter() if seen is None else seen
    out: list[str] = []
    for it in items:
        if it.kind in ("user", "assistant"):
            h = _h(it.text + ("|int" if it.interrupted else ""))
            key = f"{it.kind}:{h}"
            out.append(stable_id(session_key, it.kind, h, seen[key]))
            seen[key] += 1
        elif it.kind == "call":
            out.append(stable_id(session_key, "proposed", it.call_id or _h(json.dumps(it.input))))
        else:
            out.append(stable_id(session_key, "result", it.call_id or _h(it.text)))
    return out


def events_for_item(item: HistoryItem, event_id: str, ctx: NormalizeContext) -> list[AgentEvent]:
    """Primary event plus derived typed events for one history item."""
    base: dict[str, Any] = {
        "workspace_id": ctx.workspace_id,
        "session_id": ctx.session_key,
        "timestamp": ctx.now,
    }
    if item.kind == "user":
        return [
            AgentEvent(
                event_id=event_id,
                event_type=EventType.USER_MESSAGE,
                content_hash=_h(item.text),
                metadata={"chars": len(item.text), "interrupted": item.interrupted},
                source_ref=f"msg:{item.index}",
                transient={"text": item.text, "interrupted": item.interrupted},
                **base,
            )
        ]
    if item.kind == "assistant":
        return [
            AgentEvent(
                event_id=event_id,
                event_type=EventType.ASSISTANT_MESSAGE,
                content_hash=_h(item.text),
                metadata={"chars": len(item.text)},
                source_ref=f"msg:{item.index}",
                transient={"text": item.text},
                **base,
            )
        ]
    inv = normalize_tool_call(item.name, item.input, default_cwd=ctx.cwd or ctx.project_root)
    paths = tuple(dict.fromkeys((*inv.paths_written, *inv.paths_deleted, *inv.paths_read)))
    fp = command_fingerprint(inv.command) if inv.command else None
    common: dict[str, Any] = {
        "tool_name": item.name,
        "operation": inv.family.value,
        "path_refs": paths[:32],
        "command_fingerprint": fp,
        "source_ref": f"call:{item.call_id}" if item.call_id else f"msg:{item.index}",
        **base,
    }
    if item.kind == "call":
        return [
            AgentEvent(
                event_id=event_id,
                event_type=EventType.TOOL_CALL_PROPOSED,
                metadata={"safety": inv.safety.value, "side_effect": inv.side_effect.value},
                transient={"invocation": inv, "input": item.input, "call_id": item.call_id},
                **common,
            )
        ]
    success, code = outcome_success(item.text, is_error=item.is_error)
    primary_type = (
        EventType.TOOL_CALL_FINISHED if success is not False else EventType.TOOL_CALL_FAILED
    )
    transient = {
        "invocation": inv,
        "input": item.input,
        "text": item.text,
        "call_id": item.call_id,
        "is_error": item.is_error,
        "turn": item.call_index,
    }
    meta: dict[str, Any] = {"chars": len(item.text), "safety": inv.safety.value}
    events = [
        AgentEvent(
            event_id=event_id,
            event_type=primary_type,
            exit_code=code,
            success=success,
            content_hash=_h(item.text),
            metadata=meta,
            transient=transient,
            **common,
        )
    ]
    events.extend(_derived(inv, item, event_id, success, code, common, transient))
    return events


def _derived(
    inv: ToolInvocation,
    item: HistoryItem,
    parent_id: str,
    success: bool | None,
    code: int | None,
    common: dict[str, Any],
    transient: dict[str, Any],
) -> list[AgentEvent]:
    out: list[AgentEvent] = []

    def add(etype: EventType, key: str, **extra: Any) -> None:
        payload = {**common, **extra}
        out.append(
            AgentEvent(
                event_id=stable_id(parent_id, etype.value, key),
                event_type=etype,
                exit_code=code,
                success=success,
                transient=transient,
                **payload,
            )
        )

    for p in inv.paths_written:
        add(EventType.FILE_WRITE, p, path_refs=(p,))
    for p in inv.paths_deleted:
        add(EventType.FILE_DELETE, p, path_refs=(p,))
    if inv.family is Family.READ_FILE:
        for p in inv.paths_read:
            add(EventType.FILE_READ, p, path_refs=(p,))
    if inv.family is Family.TEST:
        parsed = parse_test_output(item.text, inv.test_framework)
        meta: dict[str, Any] = {"framework": inv.test_framework}
        if parsed is not None:
            meta.update(passed=parsed.passed, failed=parsed.failed, errors=parsed.errors)
        add(EventType.TEST_RUN, "test", metadata=meta)
    elif inv.family is Family.BUILD:
        add(EventType.BUILD_RUN, "build")
    elif inv.family in (Family.SEARCH_TEXT, Family.LIST_FILES):
        add(EventType.SEARCH_RUN, "search")
    elif inv.family is Family.GIT:
        add(EventType.GIT_STATE, "git")
    if inv.command:
        add(EventType.COMMAND_RUN, "cmd")
    return out
